// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-designs/ElegantSplit.tsx": () => import("../components/mockups/login-designs/ElegantSplit.tsx"),
  "./components/mockups/login-designs/FullCover.tsx": () => import("../components/mockups/login-designs/FullCover.tsx"),
  "./components/mockups/login-designs/MinimalCard.tsx": () => import("../components/mockups/login-designs/MinimalCard.tsx")
};
